// Mock data for student health records
export const mockStudentHealth = [
  {
    id: "S001",
    code: "HS001",
    name: "Nguyễn Minh An",
    className: "Mầm 1",
    height: 105,
    weight: 16.5,
    status: "Khỏe mạnh",
    bloodType: "O+",
    vaccinations: ["Sốt xuất huyết", "Bại liệt", "Viêm gan B"],
    medicalConditions: [],
    allergies: "Không",
    lastCheckup: "2025-09-15",
    nextCheckup: "2026-03-15",
    notes: "Sức khỏe bình thường, cần tập thể dục thường xuyên",
  },
  {
    id: "S002",
    code: "HS002",
    name: "Trần Thảo My",
    className: "Mầm 1",
    height: 103,
    weight: 15.8,
    status: "Khỏe mạnh",
    bloodType: "B+",
    vaccinations: ["Sốt xuất huyết", "Bại liệt", "Viêm gan B"],
    medicalConditions: [],
    allergies: "Không",
    lastCheckup: "2025-09-15",
    nextCheckup: "2026-03-15",
    notes: "Sức khỏe tốt",
  },
  {
    id: "S003",
    code: "HS003",
    name: "Lê Hoàng Nam",
    className: "Chồi 2",
    height: 110,
    weight: 18.2,
    status: "Cần theo dõi",
    bloodType: "A+",
    vaccinations: ["Sốt xuất huyết", "Bại liệt", "Viêm gan B"],
    medicalConditions: ["Cận thị"],
    allergies: "Phấn hoa",
    lastCheckup: "2025-10-01",
    nextCheckup: "2026-04-01",
    notes: "Cần đi kiểm tra mắt, hạn chế tiếp xúc phấn hoa",
  },
  {
    id: "S004",
    code: "HS004",
    name: "Phạm Thu Hà",
    className: "Chồi 1",
    height: 108,
    weight: 17.0,
    status: "Khỏe mạnh",
    bloodType: "AB+",
    vaccinations: ["Sốt xuất huyết", "Bại liệt", "Viêm gan B"],
    medicalConditions: [],
    allergies: "Không",
    lastCheckup: "2025-09-20",
    nextCheckup: "2026-03-20",
    notes: "Khỏe mạnh, phát triển bình thường",
  },
  {
    id: "S005",
    code: "HS005",
    name: "Võ Minh Quân",
    className: "Lá 1",
    height: 115,
    weight: 19.5,
    status: "Khỏe mạnh",
    bloodType: "O+",
    vaccinations: ["Sốt xuất huyết", "Bại liệt", "Viêm gan B", "Cúm"],
    medicalConditions: [],
    allergies: "Không",
    lastCheckup: "2025-08-10",
    nextCheckup: "2026-02-10",
    notes: "Phát triển bình thường, sức khỏe xuất sắc",
  },
]

export const healthStatusOptions = [
  { value: "all", label: "Tất cả" },
  { value: "Khỏe mạnh", label: "Khỏe mạnh" },
  { value: "Cần theo dõi", label: "Cần theo dõi" },
  { value: "Cần điều trị", label: "Cần điều trị" },
]

export const allClasses = [
  "Mầm 1",
  "Mầm 2",
  "Mầm 3",
  "Chồi 1",
  "Chồi 2",
  "Lá 1",
]
